title: CodersHigh
description: Winternship@IIT Ropar
author: Sudarshan
theme: minima      # uses the default GitHub Pages theme
plugins:
  - jekyll-feed   # optional: adds an RSS feed
baseurl: ""        # leave blank for project repositories
